[package]
name = "backend"
version.workspace = true
edition.workspace = true

[dependencies]
actix-cors = "0.7"
actix-web = "4"
argon2 = "0.5"
chrono.workspace = true
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls"] }
serde.workspace = true
serde_json.workspace = true
shared.workspace = true
sqlx = { version = "0.8", features = ["postgres", "runtime-tokio", "tls-rustls", "uuid", "chrono", "migrate", "json"] }
thiserror = "2"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
uuid.workspace = true

[dev-dependencies]
actix-http = "3"

[lints]
workspace = true
